name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22.x'

    - uses: pnpm/action-setup@v4

    - name: Build
      run: |
        pnpm install
        pnpm build
        
    - name: Test
      run: pnpm test
